# Start with the official Go image
FROM golang:1.22

# Set the working directory
WORKDIR /app

# Copy go.mod and go.sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the rest of the application
COPY . .

# Build the application
RUN go build -o main .

# Command to run the application
#CMD ["./main"]
CMD [ "./main", "listen" ]
